#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx
  - certbot
  - python3-certbot-nginx
  - ufw
  # I need node as well, but the version for ubuntu is older than I'd like. on
  # the actual server, I'm just downloading the tarball and moving it to
  # /usr/local/bin

users:
  - name: deploy
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    # Make sure to include a deployment machine's public key here, or else you
    # will lock yourself out of the server! Depending on your provider, you may
    # not be able to access the machine at all, and need to recreate it.
    # You can add more keys later, such as for CI/CD, another machine, etc.
    ssh_authorized_keys:
      - ssh-rsa REPLACE_ME foo@example.com

runcmd:
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable

  - mkdir -p /var/www/pdxcandc
  - chown deploy:deploy /var/www/pdxcandc

  - rm /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - systemctl start nginx

  - mkdir -p /var/log/journal
  - mkdir -p /etc/systemd/journald.conf.d
  - systemd-tmpfiles --create --prefix /var/log/journal
  - systemctl restart systemd-journald

  # double check the version here!
  - curl -O https://nodejs.org/dist/v22.14.0/node-v22.14.0-linux-x64.tar.xz
  # I actually only want bin/node
  - tar xf node-v22.14.0-linux-x64.tar.xz 
  - mkdir -p /usr/local/bin
  - mv node-v22.14.0-linux-x64/bin/node /usr/local/bin/node
  - rm -rf node-v22.14.0-linux-x64
  - rm node-v22.14.0-linux-x64.tar.xz

write_files:
  - path: /etc/systemd/journald.conf.d/50-pdxcandc-journald.conf
    content: |
      [Journal]
      SystemMaxUse=100M
      MaxRetentionSec=7d
      Compress=yes
      ForwardToSyslog=yes
      Storage=persistent
  - path: /etc/ssh/sshd_config.d/custom.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
    owner: root:root
    permissions: '0644'

system_info:
  default_user:
    shell: /bin/bash

timezone: America/Los_Angeles