#cloud-config

package_update: true
package_upgrade: true

packages:
  - nginx
  - certbot
  - python3-certbot-nginx
  - ufw

users:
  - name: deploy
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa REPLACE_ME

runcmd:
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable

  - mkdir -p /var/www/pdxcandc
  - chown deploy:deploy /var/www/pdxcandc

  - ln -s /etc/nginx/sites-available/pdxcandc.conf /etc/nginx/sites-enabled/
  - rm /etc/nginx/sites-enabled/default
  - systemctl enable nginx
  - systemctl start nginx

write_files:
  - path: /etc/ssh/sshd_config.d/custom.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
    owner: root:root
    permissions: '0644'

system_info:
  default_user:
    shell: /bin/bash

timezone: America/Los_Angeles